[package]
name = "stoik-gui"
version = "0.0.0"
edition = "2021"
authors = ["htmlcsjs"]

[dependencies]
stoik = { path = "../stoik" }
eframe = "0.21"
egui = "0.21"

[build-dependencies]
image = "0.24"
