[package]
name = "stoik-cli"
version = "0.0.0"
edition = "2021"
default-run = "stoik-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stoik = { path = "../stoik" }


